### ISSUE TITLE
ellie throws RuntimeError: float unrepresentable in integer range on some inputs

### ISSUE THREAD

**Issue by andersk** [nearform/node-cephes#7] opened 2019-09-16 02:24 UTC
```
> const cephes = require("cephes");
undefined
> cephes.ellie(1.0731208831306067, 0.9128794812874865)
Thrown:
RuntimeError: float unrepresentable in integer range
    at _cephes_ellie (wasm-function[27]:303)
    at Object.ellie (/home/anders/Desktop/sphere/node_modules/cephes/index.js:1746:25)
```

Based on similar bug reports in other projects, this may be fixable by [compiling with `BINARYEN_TRAP_MODE='clamp'`](https://emscripten.org/docs/compiling/WebAssembly.html#binaryen-codegen-options).

**Comment by PhanindraNeralla** [comment] 2024-02-19 08:22
Tried adding `BINARYEN_TRAP_MODE='clamp'` but unable to verify as download and build are failing.
Faced multiple issues related to `clang-remake`, `clang-format`, `emcc` command related executions.
Faced multiple dependency related issues upon fixing other related issue. 
Tried adding them but couldnot make much progress.

Hence moving this back to TODO.

**Comment by puskin94** [comment] 2024-05-09 18:44
@simoneb this should be closed too. It should have been fixed with https://github.com/nearform/node-cephes/pull/16

**Closed** 2024-05-09 18:47 UTC

**Comment by andersk** [comment] 2024-05-09 19:14
With cephes 2.0.0, the same test case returns `NaN`, which is not the right answer; it should be `0.8994413957643846`. Should I open a new issue?

**Comment by puskin94** [comment] 2024-05-09 19:19
> With cephes 2.0.0, the same test case returns `NaN`, which is not the right answer; it should be `0.8994413957643846`. Should I open a new issue?

please do so! I have the feeling the issue is occurring because of some discrepancy at built time, worth opening an issue to dig into it :)
